---
- hosts: vmlab
  become: yes
  vars:
    seneca_id: ssuresh14
  tasks:
    - name: Update Apache (httpd) to latest version
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository if not installed
      yum:
        name: epel-release
        state: present

    - name: Remove tree package if installed
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create new user with sudo access
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        append: yes
        state: present
        create_home: yes

    - name: Create .ssh directory for new user
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: 0700

    - name: Add SSH public key for new user
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Create directory structure for labs
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: 0755
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8

